//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaStarsUpPlanner.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GorevDurumları
    {
        public int GorevDurumId { get; set; }
        public Nullable<int> GorevId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> GorevDurumTarihi { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public string YapilacakIs1 { get; set; }
        public string YapilacakIs2 { get; set; }
        public string YapilacakIs3 { get; set; }
        public string YapilacakIs4 { get; set; }
    
        public virtual Durumlar Durumlar { get; set; }
        public virtual Gorevler Gorevler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
