//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaStarsUpPlanner.Models.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gorevler()
        {
            this.GorevDurumları = new HashSet<GorevDurumları>();
        }
        public int GorevId { get; set; }
        public string GorevAdi { get; set; }
        public string Aciklama { get; set; }
        public string Notlar { get; set; }
        public Nullable<System.DateTime> GorevTarih { get; set; }
        public Nullable<System.DateTime> TahminiTarih { get; set; }
        public Nullable<System.DateTime> GerceklesenTarih { get; set; }
        public Nullable<int> KullaniciId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GorevDurumları> GorevDurumları { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
