//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaStarsUpPlanner.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStarsUpPlannerEntities : DbContext
    {
        public dbStarsUpPlannerEntities()
            : base("name=dbStarsUpPlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Durumlar> Durumlar { get; set; }
        public virtual DbSet<GorevDurumları> GorevDurumları { get; set; }
        public virtual DbSet<Gorevler> Gorevler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
